model_list:
  - model_name: llama-local
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://zoe-ollama:11434
  - model_name: gpt-3.5
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-instant
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY

router_settings:
  routing_strategy: "simple-shuffle"
  num_retries: 3
  timeout: 60

general_settings:
  master_key: "sk-1234"  # Change this to a secure key
  disable_database_usage: true
