version: '3.8'
services:
  zoe-n8n:
    image: n8nio/n8n:latest
    container_name: zoe-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://zoe-core:8000
      - N8N_EDITOR_BASE_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
      - ./services/zoe-n8n/workflows:/home/node/workflows
    networks:
      - zoe-network
    restart: unless-stopped
    depends_on:
      - zoe-core

volumes:
  n8n_data:

networks:
  zoe-network:
    external: true
