/**
 * Seam-A sentinel stream contract tests (LAB-ONLY, offline).
 *
 * THE SENTINEL BYTES ARE THE LOAD-BEARING THING. The prod consumer
 * (services/zoe-data: routers/chat.py, routers/voice_tts.py) dispatches on
 * `chunk.startswith("__TOOL__:")` / `("__THINKING__:")` and json-parses the
 * `__TOOL__` payload that services/zoe-data/zoe_core_client.py builds with
 * CPython `json.dumps` (DEFAULT separators `", "`/`": "`, ensure_ascii).
 * Every expected string below was generated by running that exact
 * `json.dumps` call in CPython 3 and pasting the output — if one of these
 * assertions fails, the sidecar has drifted off the prod brain's wire bytes.
 *
 * Also covers the event→chunk reducer against a scripted fake model/tool run
 * and the NDJSON streaming middleware end-to-end (fake observe(), fake Hono
 * context — no network, no model).
 *
 * Run (Node 22, type-stripping):
 *   node --experimental-strip-types --test test/sentinel_stream.test.ts
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';

import {
  NDJSON_CONTENT_TYPE,
  ndjsonLine,
  newSeamAState,
  pyJsonDumps,
  seamAFrames,
  seamAStreamingMiddleware,
  toolArgsSentinel,
  toolResultSentinel,
  toolStartSentinel,
} from '../src/streaming.ts';

// ─── pyJsonDumps: byte parity with CPython json.dumps ────────────────────────

test('phase=start sentinel matches CPython json.dumps byte-for-byte', () => {
  assert.equal(
    toolStartSentinel('call_1', 'get_weather'),
    '__TOOL__:{"phase": "start", "id": "call_1", "name": "get_weather"}',
  );
});

test('phase=args sentinel: nested args, non-ASCII, quotes, newlines, null, bool, list', () => {
  const sentinel = toolArgsSentinel('call_1', 'get_weather', {
    location: 'Nabiac café',
    days: 3,
    detail: null,
    metric: true,
    tags: ['a b', 'q"x'],
    note: 'line1\nline2',
  });
  // Pinned from: python3 -c 'import json; print("__TOOL__:" + json.dumps({...}))'
  assert.equal(
    sentinel,
    '__TOOL__:{"phase": "args", "id": "call_1", "name": "get_weather", '
    + '"args": {"location": "Nabiac caf\\u00e9", "days": 3, "detail": null, '
    + '"metric": true, "tags": ["a b", "q\\"x"], "note": "line1\\nline2"}}',
  );
});

test('phase=args: missing/null arguments become {} (mirrors `arguments or {}`)', () => {
  assert.equal(
    toolArgsSentinel('c1', 't', undefined),
    '__TOOL__:{"phase": "args", "id": "c1", "name": "t", "args": {}}',
  );
  assert.equal(
    toolArgsSentinel('c1', 't', null),
    '__TOOL__:{"phase": "args", "id": "c1", "name": "t", "args": {}}',
  );
});

test('ensure_ascii parity: astral emoji → surrogate pair, control chars, named escapes', () => {
  // Pinned from: json.dumps({"e": "🙂", "c": "\x01\x1f\x7f", "t": "\t\r\b\f"})
  assert.equal(
    pyJsonDumps({ e: '🙂', c: '\x01\x1f\x7f', t: '\t\r\b\f' }),
    '{"e": "\\ud83d\\ude42", "c": "\\u0001\\u001f\\u007f", "t": "\\t\\r\\b\\f"}',
  );
});

// ─── toolResultSentinel: mirrors zoe_core_client._tool_result_sentinel ───────

test('phase=result: string result passes through verbatim (ensure_ascii applied)', () => {
  const s = toolResultSentinel({ type: 'tool', toolCallId: 'call_1', result: 'Sunny, 21°C.' });
  // Pinned from: json.dumps({"phase": "result", "id": "call_1", "result": "Sunny, 21°C."})
  assert.equal(s, '__TOOL__:{"phase": "result", "id": "call_1", "result": "Sunny, 21\\u00b0C."}');
});

test('phase=result: non-string result stringified COMPACT (json.dumps separators=(",",":"))', () => {
  const s = toolResultSentinel({
    type: 'tool',
    toolCallId: 'call_1',
    result: { ok: true, items: ['milk', 'café'], n: 2 },
  });
  // Inner compact dump pinned from CPython; note the nested envelope unwrap
  // does NOT trigger (no content/text/output/result key inside).
  assert.equal(
    s,
    '__TOOL__:{"phase": "result", "id": "call_1", '
    + '"result": "{\\"ok\\":true,\\"items\\":[\\"milk\\",\\"caf\\\\u00e9\\"],\\"n\\":2}"}',
  );
});

test('phase=result: one nested envelope level is unwrapped (content/text/output/result)', () => {
  assert.equal(
    toolResultSentinel({ type: 'tool', toolCallId: 'c1', result: { content: 'hi' } }),
    '__TOOL__:{"phase": "result", "id": "c1", "result": "hi"}',
  );
  assert.equal(
    toolResultSentinel({ type: 'tool', toolCallId: 'c1', result: { text: 'hi' } }),
    '__TOOL__:{"phase": "result", "id": "c1", "result": "hi"}',
  );
  // top-level probe order: result, then output, then content
  assert.equal(
    toolResultSentinel({ type: 'tool', toolCallId: 'c1', output: 'out' }),
    '__TOOL__:{"phase": "result", "id": "c1", "result": "out"}',
  );
});

test('phase=result: id-only and nothing-at-all shapes (mirror prod exactly)', () => {
  assert.equal(
    toolResultSentinel({ type: 'tool', toolCallId: 'call_9' }),
    '__TOOL__:{"phase": "result", "id": "call_9"}',
  );
  assert.equal(
    toolResultSentinel({ type: 'tool', result: 'done' }),
    '__TOOL__:{"phase": "result", "result": "done"}',
  );
  assert.equal(toolResultSentinel({ type: 'tool' }), null);
});

// ─── seamAFrames: the Flue-event → Seam-A chunk reducer ──────────────────────

test('scripted tool run maps to the exact prod chunk sequence, in order', () => {
  const state = newSeamAState();
  const chunks: string[] = [];
  const script: Array<Record<string, unknown>> = [
    // assistant asks for a tool (complete message with the full arguments)
    {
      type: 'message_end',
      message: {
        role: 'assistant',
        content: [{ type: 'toolCall', id: 'call_1', name: 'get_weather', arguments: { forecast: false } }],
      },
    },
    // execution begins — start already emitted at message_end, must dedupe
    { type: 'tool_start', toolName: 'get_weather', toolCallId: 'call_1' },
    // execution ends with the tool's string result
    { type: 'tool', toolName: 'get_weather', toolCallId: 'call_1', isError: false, result: 'Sunny, 21°C.', durationMs: 42 },
    // the model synthesizes the answer as live deltas
    { type: 'text_delta', text: 'It looks ' },
    { type: 'text_delta', text: 'sunny.' },
    // final assistant message (complete) — deltas already streamed, no frames
    { type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'It looks sunny.' }] } },
  ];
  for (const ev of script) chunks.push(...seamAFrames(ev, state));
  assert.deepEqual(chunks, [
    '__TOOL__:{"phase": "start", "id": "call_1", "name": "get_weather"}',
    '__TOOL__:{"phase": "args", "id": "call_1", "name": "get_weather", "args": {"forecast": false}}',
    '__TOOL__:{"phase": "result", "id": "call_1", "result": "Sunny, 21\\u00b0C."}',
    'It looks ',
    'sunny.',
  ]);
  assert.equal(state.streamedText, true);
  assert.equal(state.lastAssistantText, 'It looks sunny.');
});

test('tool_start without a prior message_end still emits phase=start (shape-drift guard)', () => {
  const state = newSeamAState();
  assert.deepEqual(seamAFrames({ type: 'tool_start', toolName: 'recall_memory', toolCallId: 'c7' }, state), [
    '__TOOL__:{"phase": "start", "id": "c7", "name": "recall_memory"}',
  ]);
  // and a later message_end for the same id does not re-emit start
  const frames = seamAFrames(
    {
      type: 'message_end',
      message: { role: 'assistant', content: [{ type: 'toolCall', id: 'c7', name: 'recall_memory', arguments: {} }] },
    },
    state,
  );
  assert.deepEqual(frames, [
    '__TOOL__:{"phase": "args", "id": "c7", "name": "recall_memory", "args": {}}',
  ]);
});

test('thinking_end maps to __THINKING__:<complete text>; empty maps to nothing', () => {
  const state = newSeamAState();
  assert.deepEqual(seamAFrames({ type: 'thinking_end', content: 'checking the calendar' }, state), [
    '__THINKING__:checking the calendar',
  ]);
  assert.deepEqual(seamAFrames({ type: 'thinking_end', content: '' }, state), []);
});

test('malformed / irrelevant events map to nothing and never throw', () => {
  const state = newSeamAState();
  for (const ev of [
    { type: 'message_end' }, // no message
    { type: 'message_end', message: { role: 'user', content: 'hi' } },
    { type: 'message_end', message: { role: 'assistant', content: 'not-a-list' } },
    { type: 'message_end', message: { role: 'assistant', content: [{ type: 'toolCall', name: 'no_id' }] } },
    { type: 'tool_start', toolName: 'x' }, // no id
    { type: 'text_delta' }, // no text
    { type: 'turn_start', turnId: 't1' },
    { type: 'agent_start' },
    {},
  ] as Array<Record<string, unknown>>) {
    assert.deepEqual(seamAFrames(ev, state), []);
  }
  assert.equal(state.streamedText, false);
});

// ─── NDJSON framing ──────────────────────────────────────────────────────────

test('ndjson framing: one JSON value per line; chunks survive round-trip exactly', () => {
  const sentinel = '__TOOL__:{"phase": "start", "id": "c1", "name": "lists"}';
  const delta = 'line one\nline two'; // deltas may contain raw newlines
  assert.equal(ndjsonLine(sentinel), JSON.stringify(sentinel) + '\n');
  const line = ndjsonLine(delta);
  assert.equal(line.slice(0, -1).includes('\n'), false); // framing stays one line
  assert.equal(JSON.parse(line), delta);
  assert.equal(JSON.parse(ndjsonLine(sentinel)), sentinel);
  assert.equal(ndjsonLine({ done: true }), '{"done":true}\n');
});

// ─── Streaming middleware (fake observe + fake Hono context, offline) ────────

type Subscriber = (observation: unknown, ctx: { id?: string; agentName?: string }) => void;

function fakeHarness(opts?: {
  accept?: string;
  url?: string;
  nextStatus?: number;
}) {
  let subscriber: Subscriber | null = null;
  let unobserved = false;
  const observeFn = ((cb: Subscriber) => {
    subscriber = cb;
    return () => {
      unobserved = true;
    };
  }) as never;
  let res: Response | undefined;
  let nextCalled = false;
  const ctx = {
    req: {
      method: 'POST',
      url: opts?.url ?? 'http://sidecar.local/agents/zoe/sess-1',
      header: (name: string) => (name.toLowerCase() === 'accept' ? opts?.accept : undefined),
    },
    get res() {
      return res as Response;
    },
    set res(r: Response) {
      res = r;
    },
  };
  const next = async () => {
    nextCalled = true;
    res = new Response(JSON.stringify({ submissionId: 'sub-1' }), { status: opts?.nextStatus ?? 202 });
  };
  return {
    ctx,
    next,
    observeFn,
    emit: (ev: Record<string, unknown>, evCtx?: { id?: string }) => subscriber!(ev, evCtx ?? {}),
    get subscribed() {
      return subscriber !== null;
    },
    get unobserved() {
      return unobserved;
    },
    get nextCalled() {
      return nextCalled;
    },
  };
}

async function bodyLines(res: Response): Promise<unknown[]> {
  const text = await res.text();
  return text.split('\n').filter((l) => l.length > 0).map((l) => JSON.parse(l));
}

test('middleware streams a full tool turn as NDJSON and terminates with {"done": true}', async () => {
  const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn, timeoutMs: 5_000 });
  await mw(h.ctx as never, h.next);
  assert.equal(h.ctx.res.status, 200);
  assert.equal(h.ctx.res.headers.get('content-type'), NDJSON_CONTENT_TYPE);

  const sid = 'sess-1';
  // pre-latch noise (a previous turn still finishing) is ignored
  h.emit({ type: 'text_delta', text: 'LEAKED', instanceId: sid });
  // a foreign instance is ignored throughout
  h.emit({ type: 'operation_start', operationKind: 'prompt', operationId: 'op-x', instanceId: 'other' }, { id: 'other' });
  // our turn
  h.emit({ type: 'operation_start', operationKind: 'prompt', operationId: 'op-1', instanceId: sid });
  h.emit({
    type: 'message_end',
    instanceId: sid,
    message: {
      role: 'assistant',
      content: [{ type: 'toolCall', id: 'call_1', name: 'get_weather', arguments: { forecast: false } }],
    },
  });
  h.emit({ type: 'tool_start', toolName: 'get_weather', toolCallId: 'call_1', instanceId: sid });
  h.emit({ type: 'tool', toolName: 'get_weather', toolCallId: 'call_1', isError: false, result: 'Sunny.', durationMs: 1, instanceId: sid });
  h.emit({ type: 'text_delta', text: 'It looks ', instanceId: sid });
  h.emit({ type: 'text_delta', text: 'sunny.', instanceId: sid });
  h.emit({ type: 'text_delta', text: 'FOREIGN', instanceId: 'other' }, { id: 'other' });
  h.emit({ type: 'operation', operationKind: 'prompt', operationId: 'op-1', isError: false, instanceId: sid });

  assert.deepEqual(await bodyLines(h.ctx.res), [
    '__TOOL__:{"phase": "start", "id": "call_1", "name": "get_weather"}',
    '__TOOL__:{"phase": "args", "id": "call_1", "name": "get_weather", "args": {"forecast": false}}',
    '__TOOL__:{"phase": "result", "id": "call_1", "result": "Sunny."}',
    'It looks ',
    'sunny.',
    { done: true },
  ]);
  assert.equal(h.unobserved, true);
});

test('middleware falls back to the complete assistant text when no deltas streamed', async () => {
  const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn, timeoutMs: 5_000 });
  await mw(h.ctx as never, h.next);
  const sid = 'sess-1';
  h.emit({ type: 'operation_start', operationKind: 'prompt', operationId: 'op-1', instanceId: sid });
  h.emit({
    type: 'message_end',
    instanceId: sid,
    message: { role: 'assistant', content: [{ type: 'text', text: 'Whole answer.' }] },
  });
  h.emit({ type: 'operation', operationKind: 'prompt', operationId: 'op-1', isError: false, instanceId: sid });
  assert.deepEqual(await bodyLines(h.ctx.res), ['Whole answer.', { done: true }]);
});

test('middleware surfaces a failed prompt operation as {"error": ...}', async () => {
  const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn, timeoutMs: 5_000 });
  await mw(h.ctx as never, h.next);
  const sid = 'sess-1';
  h.emit({ type: 'operation_start', operationKind: 'prompt', operationId: 'op-1', instanceId: sid });
  h.emit({ type: 'operation', operationKind: 'prompt', operationId: 'op-1', isError: true, error: { message: 'boom' }, instanceId: sid });
  assert.deepEqual(await bodyLines(h.ctx.res), [{ error: 'boom' }]);
  assert.equal(h.unobserved, true);
});

test('middleware times out a turn that never terminates', async () => {
  const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn, timeoutMs: 20 });
  await mw(h.ctx as never, h.next);
  assert.deepEqual(await bodyLines(h.ctx.res), [{ error: 'brain turn timed out' }]);
  assert.equal(h.unobserved, true);
});

test('operation_start without an operationId never latches — id-less terminals cannot end the turn', async () => {
  const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn, timeoutMs: 30 });
  await mw(h.ctx as never, h.next);
  const sid = 'sess-1';
  h.emit({ type: 'operation_start', operationKind: 'prompt', instanceId: sid }); // no operationId
  // must NOT terminate as done ('' === '' would have): fails safe via timeout
  h.emit({ type: 'operation', operationKind: 'prompt', isError: false, instanceId: sid });
  assert.deepEqual(await bodyLines(h.ctx.res), [{ error: 'brain turn timed out' }]);
});

test('no Accept header → passthrough untouched (202 admission preserved)', async () => {
  const h = fakeHarness({});
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn });
  await mw(h.ctx as never, h.next);
  assert.equal(h.nextCalled, true);
  assert.equal(h.subscribed, false);
  assert.equal(h.ctx.res.status, 202);
});

test('?wait=result wins over the Accept header → whole-result mode untouched', async () => {
  const h = fakeHarness({
    accept: NDJSON_CONTENT_TYPE,
    url: 'http://sidecar.local/agents/zoe/sess-1?wait=result',
  });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn });
  await mw(h.ctx as never, h.next);
  assert.equal(h.subscribed, false);
  assert.equal(h.ctx.res.status, 202); // whatever flue() returned, verbatim
});

test('auth failure passes through verbatim (fail-closed route untouched)', async () => {
  const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE, nextStatus: 401 });
  const mw = seamAStreamingMiddleware({ observeFn: h.observeFn });
  await mw(h.ctx as never, h.next);
  assert.equal(h.ctx.res.status, 401);
  assert.equal(h.unobserved, true); // the pre-admission subscription is released
});

test('kill switch ZOE_BRAIN_STREAM=0 disables interception entirely', async () => {
  process.env.ZOE_BRAIN_STREAM = '0';
  try {
    const h = fakeHarness({ accept: NDJSON_CONTENT_TYPE });
    const mw = seamAStreamingMiddleware({ observeFn: h.observeFn });
    await mw(h.ctx as never, h.next);
    assert.equal(h.subscribed, false);
    assert.equal(h.ctx.res.status, 202);
  } finally {
    delete process.env.ZOE_BRAIN_STREAM;
  }
});
