from pathlib import Path

import agent_sync
from agent_sync import _build_capabilities_md, _build_zoe_self_md, _trigger_graphify_rebuild


def test_capabilities_snapshot_is_stable():
    first = _build_capabilities_md(["weather_current"], ["home-assistant"], ["chat"])
    second = _build_capabilities_md(["weather_current"], ["home-assistant"], ["chat"])

    assert first == second
    assert "Auto-generated by agent_sync from the current Zoe service inventory" in first


def test_generated_context_mentions_hermes_engineering_loop():
    zoe_self = _build_zoe_self_md(["weather_current"], ["home-assistant"], ["chat"])
    capabilities = _build_capabilities_md(["weather_current"], ["home-assistant"], ["chat"])

    assert "Hermes engineering loop" in zoe_self
    assert "source context" in zoe_self
    assert "cleanup pass" in capabilities


def test_graphify_rebuild_is_opt_in_by_default(monkeypatch):
    monkeypatch.delenv("ZOE_AGENT_SYNC_REBUILD_GRAPH", raising=False)

    assert _trigger_graphify_rebuild().startswith("skipped (set ZOE_AGENT_SYNC_REBUILD_GRAPH=true")


def test_graphify_rebuild_opt_in_env_is_recognized(monkeypatch):
    monkeypatch.setenv("ZOE_AGENT_SYNC_REBUILD_GRAPH", "true")
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setattr(agent_sync, "_GRAPHIFY_BIN", Path("/missing/graphify"))

    result = _trigger_graphify_rebuild()

    assert not result.startswith("skipped (set ZOE_AGENT_SYNC_REBUILD_GRAPH=true")
    assert result == "skipped (graphify not found at /missing/graphify)"
