from agent_sync import _build_capabilities_md, _trigger_graphify_rebuild


def test_capabilities_snapshot_is_stable():
    first = _build_capabilities_md(["weather_current"], ["home-assistant"], ["chat"])
    second = _build_capabilities_md(["weather_current"], ["home-assistant"], ["chat"])

    assert first == second
    assert "Auto-generated by agent_sync from the current Zoe service inventory" in first


def test_graphify_rebuild_is_opt_in_by_default(monkeypatch):
    monkeypatch.delenv("ZOE_AGENT_SYNC_REBUILD_GRAPH", raising=False)

    assert _trigger_graphify_rebuild().startswith("skipped (set ZOE_AGENT_SYNC_REBUILD_GRAPH=true")
