"""agent_sync.py — Generate and distribute ZOE_SELF.md to all agents.

Runs as Phase 5 of the dreaming cycle (Sunday 3am) and is also callable via:
  - POST /api/system/agent-sync
  - MCP tool: zoe_sync_knowledge

Generates:
  - ~/.openclaw/workspace/ZOE_SELF.md (full version, capped at 6000 chars)
  - ~/.hermes/SOUL.md (patches the ZOE_SELF_BEGIN/END block)
  - ~/.zoe/zoe_self_compact.txt (compact 500-char version for context prefix)
  - ~/assistant/CAPABILITIES.md (human-readable capability snapshot)

Also triggers a graphify rebuild in the background after sync (requires OPENAI_API_KEY).
"""
import asyncio
import logging
import os
import re
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

_OPENCLAW_ZOE_SELF = Path.home() / ".openclaw" / "workspace" / "ZOE_SELF.md"
_HERMES_SOUL = Path.home() / ".hermes" / "SOUL.md"
_ZOE_COMPACT = Path.home() / ".zoe" / "zoe_self_compact.txt"
_CAPABILITIES_MD = Path("/home/zoe/assistant/CAPABILITIES.md")
_GRAPHIFY_OUT = Path("/home/zoe/assistant/graphify-out")
_MAX_ZOE_SELF_CHARS = 6000
_MAX_COMPACT_CHARS = 500


async def _collect_mcp_tools() -> list[str]:
    """Collect MCP tool names from mcp_server.py's _TOOLS list."""
    try:
        from mcp_server import _TOOLS  # type: ignore[import]
        return [t.get("name", "") for t in _TOOLS if t.get("name")]
    except Exception:
        return []


async def _collect_intent_patterns() -> list[str]:
    """Collect intent names from intent_router.py."""
    try:
        import intent_router  # type: ignore[import]
        intents = []
        for attr in dir(intent_router):
            if attr.startswith("Intent") or "_RE" in attr:
                continue
            val = getattr(intent_router, attr, None)
            if callable(val) and attr.startswith("route"):
                intents.append(attr)
        return intents
    except Exception:
        return []


async def _collect_openclaw_skills() -> list[str]:
    """Collect OpenClaw skill names from workspace."""
    skills_dir = Path.home() / ".openclaw" / "workspace" / "skills"
    skills = []
    try:
        if skills_dir.exists():
            for entry in skills_dir.iterdir():
                if entry.is_dir():
                    skills.append(entry.name)
    except Exception:
        pass
    return sorted(skills)


async def _collect_ui_pages() -> list[str]:
    """Collect UI page names from the dist directory."""
    dist_dir = Path("/home/zoe/assistant/services/zoe-ui/dist")
    pages = []
    try:
        if dist_dir.exists():
            for f in dist_dir.glob("*.html"):
                pages.append(f.stem)
    except Exception:
        pass
    return sorted(pages)


def _build_zoe_self_md(
    mcp_tools: list[str],
    skills: list[str],
    ui_pages: list[str],
) -> str:
    """Build the full ZOE_SELF.md content, capped at _MAX_ZOE_SELF_CHARS."""
    lines = [
        "# ZOE_SELF.md — Live Architecture (auto-generated by agent_sync)",
        "",
        "## Agent Tiers",
        "- **Tier 0**: intent_router.py — regex fast path, <10ms, no LLM",
        "- **Tier 1**: Zoe Agent — Gemma 4 E2B @ :11434, tool loop, escalation",
        "- **Tier 1.5**: Hermes — GPT-5.4 via openai-codex @ :8642, 128k context",
        "- **Tier 2**: OpenClaw — Codex + full Playwright browser @ :18789",
        "",
        "## MCP Tools (via /api/mcp)",
    ]
    if mcp_tools:
        for t in sorted(mcp_tools):
            lines.append(f"- {t}")
    else:
        lines.append("- (tools unavailable at sync time)")
    lines += [
        "",
        "## OpenClaw Skills",
    ]
    if skills:
        for s in skills:
            lines.append(f"- {s}")
    else:
        lines.append("- (no skills installed)")
    lines += [
        "",
        "## UI Pages",
    ]
    if ui_pages:
        for p in ui_pages:
            lines.append(f"- {p}")
    lines += [
        "",
        "## Key Capabilities",
        "- Calendar, reminders, lists, notes, people (SQLite, user-scoped)",
        "- Home Assistant control (HA bridge)",
        "- Memory: MemPalace (ChromaDB semantic) + user portrait (SQLite)",
        "- Voice: Wyoming/Whisper transcribe + TTS",
        "- Push notifications: WebSocket /ws/push + proactive engine",
        "- Panel display: show_map, show_chart, show_image, open_touch_page",
        "- Web search: DDG scraping via web_search tool (no API key)",
        "- Builder skills: zoe-widget-builder, zoe-page-builder, zoe-capability-extender",
        "- Agent sync: POST /api/system/agent-sync updates this file",
        "",
        "## Escalation Guide",
        "- web_search: current events, live prices, today's news",
        "- escalate_to_openclaw: browser automation, multi-step exec, code gen, extended research",
        "- escalate_to_hermes: complex reasoning, architecture questions (no browser needed)",
    ]
    content = "\n".join(lines)
    if len(content) > _MAX_ZOE_SELF_CHARS:
        content = content[:_MAX_ZOE_SELF_CHARS - 3] + "..."
    return content


def _build_compact(mcp_tools: list[str], skills: list[str]) -> str:
    """Build a compact single-line summary, capped at _MAX_COMPACT_CHARS."""
    tool_summary = ", ".join(sorted(mcp_tools)[:12]) if mcp_tools else "calendar/reminders/lists/notes/people/HA/memory"
    skill_summary = ", ".join(skills[:5]) if skills else "widget/page/capability-extender"
    compact = (
        f"Zoe: 3-tier AI (Gemma4/Agent :11434, Hermes/GPT-5.4 :8642, OpenClaw/Codex+browser :18789). "
        f"MCP tools: {tool_summary}. Skills: {skill_summary}. "
        f"web_search (DDG), show_map/chart, HA, push, builder skills (admin+staged). "
        f"Check zoe_self_capabilities MCP. Full: ZOE_SELF.md."
    )
    if len(compact) > _MAX_COMPACT_CHARS:
        compact = compact[:_MAX_COMPACT_CHARS - 3] + "..."
    return compact


def _patch_hermes_soul(soul_path: Path, zoe_self_content: str) -> bool:
    """Patch the ZOE_SELF_BEGIN/END block in SOUL.md. Returns True if patched."""
    try:
        if not soul_path.exists():
            logger.warning("agent_sync: SOUL.md not found at %s", soul_path)
            return False
        content = soul_path.read_text()
        new_block = f"ZOE_SELF_BEGIN\n{zoe_self_content}\nZOE_SELF_END"
        if "ZOE_SELF_BEGIN" in content and "ZOE_SELF_END" in content:
            patched = re.sub(
                r"ZOE_SELF_BEGIN.*?ZOE_SELF_END",
                new_block,
                content,
                flags=re.DOTALL,
            )
        else:
            patched = content.rstrip() + f"\n\n{new_block}\n"
        soul_path.write_text(patched)
        return True
    except Exception as exc:
        logger.warning("agent_sync: SOUL.md patch failed: %s", exc)
        return False


def _build_capabilities_md(
    mcp_tools: list[str],
    skills: list[str],
    ui_pages: list[str],
) -> str:
    """Build a human-readable CAPABILITIES.md at the project root."""
    from datetime import datetime
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Zoe Capabilities",
        f"*Auto-generated by agent_sync on {ts}*",
        "",
        "## Agent Architecture",
        "| Tier | Agent | Model | Endpoint | Notes |",
        "|------|-------|-------|----------|-------|",
        "| 0 | intent_router | regex | — | <10ms fast path |",
        "| 1 | Zoe Agent | Gemma 4 E2B | :11434 | tool loop, escalation |",
        "| 1.5 | Hermes | GPT-5.4 | :8642 | 128k context, complex reasoning |",
        "| 2 | OpenClaw | Codex + browser | :18789 | Playwright, bash, skills |",
        "",
        "## MCP Tools",
    ]
    for t in sorted(mcp_tools):
        lines.append(f"- `{t}`")
    lines += [
        "",
        "## OpenClaw Skills",
    ]
    for s in sorted(skills):
        lines.append(f"- `{s}`")
    lines += [
        "",
        "## UI Pages",
    ]
    for p in sorted(ui_pages):
        lines.append(f"- [{p}](/dist/{p}.html)")
    lines += [
        "",
        "## Core Capabilities",
        "- **Memory**: MemPalace (ChromaDB semantic) + user portrait (SQLite) + open loops engine",
        "- **Calendar / Reminders / Lists / Notes / People**: SQLite, user-scoped, MCP-accessible",
        "- **Home Automation**: Home Assistant bridge (HA control, sensors, scenes)",
        "- **Voice**: Wyoming/Whisper transcription + TTS",
        "- **Push**: WebSocket /ws/push + proactive engine (morning brief, open loop follow-ups)",
        "- **Panel**: show_map, show_chart, show_image, open_touch_page, panel_browser_screenshot",
        "- **Web search**: DuckDuckGo scraping via web_search tool (no API key required)",
        "- **Self-improvement**: intent-miss review → OpenClaw pattern proposals (`self_improve` intent)",
        "- **Agent sync**: POST /api/system/agent-sync regenerates this file and all agent docs",
        "- **graphify_search**: MCP tool to query Zoe's knowledge-graph wiki (built by graphify)",
        "",
        "## Escalation Guide",
        "1. `web_search` — current events, live prices, news after training cutoff",
        "2. `escalate_to_openclaw` — browser automation, multi-step exec, code gen, scraping",
        "3. `escalate_to_hermes` — deep reasoning, architecture analysis (no browser needed)",
    ]
    return "\n".join(lines) + "\n"


def _trigger_graphify_rebuild() -> str:
    """Fire-and-forget graphify rebuild. Returns 'started' or an error string."""
    openai_key = os.environ.get("OPENAI_API_KEY", "")
    if not openai_key:
        # Try to read from .env
        env_path = Path("/home/zoe/assistant/.env")
        try:
            for line in env_path.read_text().splitlines():
                if line.startswith("OPENAI_API_KEY="):
                    openai_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                    break
        except Exception:
            pass
    if not openai_key:
        return "skipped (no OPENAI_API_KEY)"
    try:
        env = {**os.environ, "OPENAI_API_KEY": openai_key}
        proc = subprocess.Popen(
            ["graphify", "extract", ".", "--backend", "openai"],
            cwd="/home/zoe/assistant",
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        logger.info("agent_sync: graphify rebuild started (pid=%d)", proc.pid)
        return f"started (pid={proc.pid})"
    except FileNotFoundError:
        return "skipped (graphify not installed)"
    except Exception as exc:
        return f"error: {exc}"


def graphify_search(query: str) -> dict:
    """
    Search the graphify wiki for content matching query.
    Reads from graphify-out/wiki/index.md and returns relevant snippets.
    Called by the MCP graphify_search tool handler.
    """
    wiki_index = _GRAPHIFY_OUT / "wiki" / "index.md"
    if not wiki_index.exists():
        return {
            "error": "Graphify wiki not built yet. Run POST /api/system/agent-sync first.",
            "hint": "After agent-sync, graphify rebuilds in the background (~2min).",
        }

    try:
        index_content = wiki_index.read_text(errors="replace")
    except Exception as exc:
        return {"error": f"Could not read wiki index: {exc}"}

    # Extract wiki file links from the index (lines like: - [Title](filename.md))
    wiki_dir = wiki_index.parent
    link_re = re.compile(r"\[([^\]]+)\]\(([^)]+\.md)\)")
    candidates = []
    q_lower = query.lower()

    for match in link_re.finditer(index_content):
        title, filename = match.group(1), match.group(2)
        if any(kw in title.lower() or kw in filename.lower() for kw in q_lower.split()):
            candidates.append((title, filename))

    # If no title matches, do a content search over all wiki files (capped)
    if not candidates:
        wiki_files = list(wiki_dir.glob("*.md"))[:30]
        for wf in wiki_files:
            if wf.name == "index.md":
                continue
            try:
                text = wf.read_text(errors="replace")
                if q_lower in text.lower():
                    candidates.append((wf.stem, wf.name))
            except Exception:
                pass

    if not candidates:
        return {
            "results": [],
            "message": f"No wiki pages found matching '{query}'. Try broader terms.",
        }

    results = []
    for title, filename in candidates[:3]:
        wiki_file = wiki_dir / filename
        try:
            content = wiki_file.read_text(errors="replace")
            # Return first 800 chars to avoid flooding context
            snippet = content[:800]
            if len(content) > 800:
                snippet += "\n... (truncated)"
            results.append({"title": title, "file": filename, "content": snippet})
        except Exception as exc:
            results.append({"title": title, "file": filename, "error": str(exc)})

    return {"results": results, "query": query, "total_candidates": len(candidates)}


async def run_agent_sync() -> dict:
    """Run the full agent sync. Returns a status dict."""
    mcp_tools, skills, ui_pages = await asyncio.gather(
        _collect_mcp_tools(),
        _collect_openclaw_skills(),
        _collect_ui_pages(),
    )

    zoe_self = _build_zoe_self_md(mcp_tools, skills, ui_pages)
    compact = _build_compact(mcp_tools, skills)
    capabilities = _build_capabilities_md(mcp_tools, skills, ui_pages)

    results: dict = {
        "mcp_tools": len(mcp_tools),
        "skills": len(skills),
        "ui_pages": len(ui_pages),
    }

    # Write ZOE_SELF.md to OpenClaw workspace
    try:
        _OPENCLAW_ZOE_SELF.parent.mkdir(parents=True, exist_ok=True)
        _OPENCLAW_ZOE_SELF.write_text(zoe_self)
        results["openclaw_zoe_self"] = "updated"
        logger.info("agent_sync: wrote ZOE_SELF.md (%d chars) to %s", len(zoe_self), _OPENCLAW_ZOE_SELF)
    except Exception as exc:
        results["openclaw_zoe_self"] = f"error: {exc}"
        logger.warning("agent_sync: ZOE_SELF.md write failed: %s", exc)

    # Patch Hermes SOUL.md
    patched = _patch_hermes_soul(_HERMES_SOUL, zoe_self)
    results["hermes_soul"] = "patched" if patched else "skipped"

    # Write compact
    try:
        _ZOE_COMPACT.parent.mkdir(parents=True, exist_ok=True)
        _ZOE_COMPACT.write_text(compact + "\n")
        results["compact"] = "updated"
        logger.info("agent_sync: wrote compact (%d chars)", len(compact))
    except Exception as exc:
        results["compact"] = f"error: {exc}"
        logger.warning("agent_sync: compact write failed: %s", exc)

    # Write CAPABILITIES.md
    try:
        _CAPABILITIES_MD.write_text(capabilities)
        results["capabilities_md"] = "updated"
        logger.info("agent_sync: wrote CAPABILITIES.md (%d chars)", len(capabilities))
    except Exception as exc:
        results["capabilities_md"] = f"error: {exc}"
        logger.warning("agent_sync: CAPABILITIES.md write failed: %s", exc)

    # Trigger graphify rebuild in background
    graphify_result = _trigger_graphify_rebuild()
    results["graphify_rebuild"] = graphify_result
    logger.info("agent_sync: graphify rebuild: %s", graphify_result)

    results["status"] = "ok"
    return results
