"""agent_sync.py — Generate and distribute ZOE_SELF.md to all agents.

Runs as Phase 5 of the dreaming cycle (Sunday 3am) and is also callable via:
  - POST /api/system/agent-sync
  - MCP tool: zoe_sync_knowledge

Generates:
  - ~/.openclaw/workspace/ZOE_SELF.md (full version, capped at 6000 chars)
  - ~/.hermes/SOUL.md (patches the ZOE_SELF_BEGIN/END block)
  - ~/.zoe/zoe_self_compact.txt (compact 500-char version for context prefix)
  - ~/assistant/CAPABILITIES.md (human-readable capability snapshot)

Graphify rebuild is opt-in via ZOE_AGENT_SYNC_REBUILD_GRAPH=true because it
updates tracked repo files and should not dirty the live checkout on every sync.
"""
import asyncio
import json
import logging
import os
import re
from pathlib import Path

logger = logging.getLogger(__name__)

_OPENCLAW_ZOE_SELF = Path.home() / ".openclaw" / "workspace" / "ZOE_SELF.md"
_HERMES_SOUL = Path.home() / ".hermes" / "SOUL.md"
_ZOE_COMPACT = Path.home() / ".zoe" / "zoe_self_compact.txt"
_CAPABILITIES_MD = Path("/home/zoe/assistant/CAPABILITIES.md")
_MAX_ZOE_SELF_CHARS = 6000
_MAX_COMPACT_CHARS = 500
_MAX_ZOE_WHY_CHARS = 2400


async def _collect_mcp_tools() -> list[str]:
    """Collect MCP tool names from mcp_server.py's _TOOLS list."""
    try:
        from mcp_server import TOOLS  # type: ignore[import]
        return [t.get("name", "") for t in TOOLS if t.get("name")]
    except Exception:
        return []


async def _collect_intent_patterns() -> list[str]:
    """Collect intent names from intent_router.py."""
    try:
        import intent_router  # type: ignore[import]
        intents = []
        for attr in dir(intent_router):
            if attr.startswith("Intent") or "_RE" in attr:
                continue
            val = getattr(intent_router, attr, None)
            if callable(val) and attr.startswith("route"):
                intents.append(attr)
        return intents
    except Exception:
        return []


async def _collect_openclaw_skills() -> list[str]:
    """Collect OpenClaw skill names from workspace."""
    skills_dir = Path.home() / ".openclaw" / "workspace" / "skills"
    skills = []
    try:
        if skills_dir.exists():
            for entry in skills_dir.iterdir():
                if entry.is_dir():
                    skills.append(entry.name)
    except Exception:
        pass
    return sorted(skills)


async def _collect_ui_pages() -> list[str]:
    """Collect UI page names from the dist directory."""
    dist_dir = Path("/home/zoe/assistant/services/zoe-ui/dist")
    pages = []
    try:
        if dist_dir.exists():
            for f in dist_dir.glob("*.html"):
                pages.append(f.stem)
    except Exception:
        pass
    return sorted(pages)


def _build_zoe_self_md(
    mcp_tools: list[str],
    skills: list[str],
    ui_pages: list[str],
) -> str:
    """Build the full ZOE_SELF.md content, capped at _MAX_ZOE_SELF_CHARS."""
    lines = [
        "# ZOE_SELF.md — Live Architecture (auto-generated by agent_sync)",
        "",
        "## Agent Tiers",
        "- **Tier 0**: intent_router.py — regex fast path, <10ms, no LLM",
        "- **Tier 1**: Zoe Agent — Gemma 4 E4B-QAT @ :11434, tool loop, escalation",
        "- **Tier 1.5**: Hermes — default engineering/reasoning agent @ :8642, 128k context",
        "- **Tier 2**: OpenClaw — installed but not an active executor unless operator-enabled",
        "",
        "## MCP Tools (via /api/mcp)",
    ]
    if mcp_tools:
        for t in sorted(mcp_tools):
            lines.append(f"- {t}")
    else:
        lines.append("- (tools unavailable at sync time)")
    lines += [
        "",
        "## OpenClaw Skills",
    ]
    if skills:
        for s in skills:
            lines.append(f"- {s}")
    else:
        lines.append("- (no skills installed)")
    lines += [
        "",
        "## UI Pages",
    ]
    if ui_pages:
        for p in ui_pages:
            lines.append(f"- {p}")
    lines += [
        "",
        "## Key Capabilities",
        "- Calendar, reminders, lists, notes, people (PostgreSQL, user-scoped)",
        "- Home Assistant control (HA bridge)",
        "- Memory: MemPalace (ChromaDB semantic) + user portrait (SQLite)",
        "- Voice: Wyoming/Whisper transcribe + TTS",
        "- Push notifications: WebSocket /ws/push + proactive engine",
        "- Panel display: show_map, show_chart, show_image, open_touch_page",
        "- Web search: DDG scraping via web_search tool (no API key)",
        "- Builder skills: zoe-widget-builder, zoe-page-builder, zoe-capability-extender",
        "- Hermes engineering loop: source context → small feature → cleanup pass → review/test",
        "- Agent sync: POST /api/system/agent-sync updates this file",
        "",
        "## Escalation Guide",
        "- web_search: current events, live prices, today's news",
        "- escalate_to_hermes: default for complex tasks, engineering, architecture, code review, planning, board repair, and Greptile loops",
        "- escalate_to_openclaw: available as an explicit/manual fallback; Hermes is the default escalation path",
        "",
        "## Services & Ports",
        "- zoe-data (host uvicorn) :8000 — main chat API, AG-UI SSE, MCP server",
        "- zoe-auth :8002 — JWT auth, RBAC",
        "- zoe-ui :80/:443 — Nginx, serves chat/dashboard/settings/touch pages",
        "- homeassistant-mcp-bridge :8007 — HA tool bridge",
        "- zoe-database (PostgreSQL) :5432 — shared primary DB for Zoe + Multica",
        "- multica-backend :8080 — Multica board API (agent approval flows)",
        "- multica-web :3000 — Multica UI",
        "- hermes-agent :8642 — GPT-5.4/Codex gateway",
        "- openclaw-gateway :18789 — OpenClaw ACP gateway",
        "- llama-server (host) :11434 — local LLM (Gemma 4 E4B-QAT)",
        "",
        "## A2A Federation",
        "- /.well-known/agent.json — Zoe's public A2A agent card",
        "- GET /api/agent/registry — list of registered peer agents (OpenClaw, Hermes)",
        "- GET /api/agent/squad — squad topology (capabilities, health)",
        "- GET /api/agent/runtimes — last probe timestamps per agent",
        "- POST /api/agent/tasks — queue a task via background_runner (Hermes executes)",
        "- MCP tool: a2a_delegate — delegate tasks to named agents from tool loop",
        "- Depth guard: MAX_REQUEST_DEPTH=3 in background_runner.py",
        "",
        "## Multica Board Integration",
        "- Board at multica-backend :8080 / multica-web :3000",
        "- Workspace: 'Zoe Evolution' (MULTICA_WORKSPACE_ID in .env)",
        "- self_improve and extend_capability intents → create Multica issues for approval",
        "- POST /api/agent/board/approve|review|cancel — act on issues from chat",
        "- Poll loop in main.py syncs background task completion → Multica issue status",
        "",
        "## Self-Evolution Loop (NOTICE→PROPOSE→EXECUTE→MEASURE)",
        "- NOTICE: nightly run_evolution_notice() — clusters intent misses (llm_call_log),",
        "  detects LLM error spikes, records user frustration signals",
        "- PROPOSE: writes to evolution_proposals (status=pending)",
        "- EXECUTE: user approves in chat or settings; background_runner queues Hermes task",
        "  and sets proposal status=deployed on completion",
        "- MEASURE: run_measure_phase() after 48h — sets status=validated or failed",
        "- Weekly digest: EvolutionWeeklyDigestTrigger fires Friday 6pm",
        "- GET /api/agent/evolution/proposals — all proposals",
    ]
    content = "\n".join(lines)
    if len(content) > _MAX_ZOE_SELF_CHARS:
        content = content[:_MAX_ZOE_SELF_CHARS - 3] + "..."
    return content


def _build_compact(mcp_tools: list[str], skills: list[str]) -> str:
    """Build a compact single-line summary, capped at _MAX_COMPACT_CHARS."""
    tool_summary = ", ".join(sorted(mcp_tools)[:12]) if mcp_tools else "calendar/reminders/lists/notes/people/HA/memory"
    skill_summary = ", ".join(skills[:5]) if skills else "widget/page/capability-extender"
    compact = (
        f"Zoe: 3-tier AI (Gemma4/Agent :11434, Hermes/default engineering+browser :8642, OpenClaw available fallback :18789). "
        f"MCP tools: {tool_summary}. Skills: {skill_summary}. "
        f"web_search (DDG), show_map/chart, HA, push, builder skills (admin+staged). "
        f"Check zoe_self_capabilities MCP. Full: ZOE_SELF.md."
    )
    if len(compact) > _MAX_COMPACT_CHARS:
        compact = compact[:_MAX_COMPACT_CHARS - 3] + "..."
    return compact


def _build_zoe_why() -> str:
    """Build the ZOE_WHY block: Zoe's mission + charter, condensed for SOUL.md.

    This teaches engineering agents (Hermes) *why* Zoe exists so they make better
    design calls, not just the port map.

    NOTE: The content below is intentionally hand-curated (distilled from
    docs/governance/ZOE_DESIGN_PRINCIPLES.md), not dynamically read from that file.
    When the charter changes, update this function to keep the SOUL.md block in sync.
    Kept lean per charter S9 (minimize structure), not the full charter pasted in.
    """
    content = (
        "# ZOE_WHY.md — Zoe's mission & charter (auto-generated by agent_sync)\n"
        "Distilled from: docs/governance/ZOE_DESIGN_PRINCIPLES.md (hand-curated — update\n"
        "_build_zoe_why() when the charter changes). At the start of any Zoe engineering\n"
        "task, read the charter section relevant to your change and consult the\n"
        "codebase-memory MCP for code-graph/architecture context (graphify is retired);\n"
        "honor the universality + harness rules below.\n"
        "\n"
        "## North Star\n"
        "Zoe is one continuous identity: ambient presence,\n"
        "judgment over walls, and trust that grows per user/tool. She is a being users have\n"
        "a relationship with — never an attention/engagement machine.\n"
        "\n"
        "## Who is speaking\n"
        "One Zoe instance per site, many users. Every turn pivots on 'who is speaking now'\n"
        "(speaker auth primary; touch/device pairing fallback).\n"
        "\n"
        "## Memory scopes (never write unscoped)\n"
        "- personal: private to one user; user A's personal scope is never visible to user B.\n"
        "- shared: household/business data (lists, family calendar, inventory).\n"
        "- ambient: environment observations (sensors, room/usage state).\n"
        "\n"
        "## Trust envelopes\n"
        "Every world-changing action goes through a proposal path, auto-approved only at low\n"
        "stakes. Trust expands per user/tool, not via a global switch.\n"
        "\n"
        "## Universality (hard rules — never violate)\n"
        "- No home/family/household concepts in the kernel (router, memory schema, auth, tools).\n"
        "- Credentials keyed per user and per scope; no personal creds in global env vars.\n"
        "- Tools register via an allow-list mechanism.\n"
        "- Experts/skills are filesystem files, discovered by the router.\n"
        "- Core runs on non-Jetson hardware without surgery.\n"
        "\n"
        "## Harness-first engineering (charter S9/S10)\n"
        "The harness is the product: prefer routing/prompt/memory/tool-contract improvements\n"
        "before bigger models. Minimize structure; ablate don't stack; representation over\n"
        "brittle Python. Think before coding, simplicity first, surgical changes, verify.\n"
        "\n"
        "## Product context — the bigger why\n"
        "Zoe is the AI Assistant layer (component #16) of **the411.life** (the Living Map of\n"
        "Social Life) and its **Nudge** wedge — privacy-first, real-world-connection-first.\n"
        "We are actively building toward the411: Zoe stays Zoe (identity/charter primary) and\n"
        "the411 extends her abilities, knowledge, and connection. Favor the411-aligned designs;\n"
        "where a change would answer a charter open question, say so — don't decide silently."
    )
    if len(content) > _MAX_ZOE_WHY_CHARS:
        content = content[:_MAX_ZOE_WHY_CHARS - 3] + "..."
    return content


def _patch_hermes_soul(soul_path: Path, block_content: str, marker: str = "ZOE_SELF") -> bool:
    """Patch a <marker>_BEGIN/END block in SOUL.md. Returns True if patched.

    Used for both the ZOE_SELF (live architecture) and ZOE_WHY (mission/charter)
    blocks so the dreaming-cycle sync regenerates them in place rather than letting
    a hand-edit drift or get clobbered.
    """
    begin, end = f"{marker}_BEGIN", f"{marker}_END"
    try:
        if not soul_path.exists():
            logger.warning("agent_sync: SOUL.md not found at %s", soul_path)
            return False
        content = soul_path.read_text()
        new_block = f"{begin}\n{block_content}\n{end}"
        if begin in content and end in content:
            patched = re.sub(
                re.escape(begin) + r".*?" + re.escape(end),
                lambda _m: new_block,
                content,
                flags=re.DOTALL,
            )
        else:
            patched = content.rstrip() + f"\n\n{new_block}\n"
        soul_path.write_text(patched)
        return True
    except Exception as exc:
        logger.warning("agent_sync: SOUL.md %s patch failed: %s", marker, exc)
        return False


def _build_capabilities_md(
    mcp_tools: list[str],
    skills: list[str],
    ui_pages: list[str],
) -> str:
    """Build a human-readable CAPABILITIES.md at the project root."""
    lines = [
        "# Zoe Capabilities",
        "*Auto-generated by agent_sync from the current Zoe service inventory*",
        "",
        "## Agent Architecture",
        "| Tier | Agent | Model | Endpoint | Notes |",
        "|------|-------|-------|----------|-------|",
        "| 0 | intent_router | regex | — | <10ms fast path |",
        "| 1 | Zoe Agent | Gemma 4 E4B-QAT | :11434 | tool loop, escalation |",
        "| 1.5 | Hermes | GPT-5.4 | :8642 | default engineering, planning, review, repair |",
        "| 2 | OpenClaw | Gemma 4 E4B-QAT + browser | :18789 | available fallback, not default route |",
        "",
        "## MCP Tools",
    ]
    for t in sorted(mcp_tools):
        lines.append(f"- `{t}`")
    lines += [
        "",
        "## OpenClaw Skills",
    ]
    for s in sorted(skills):
        lines.append(f"- `{s}`")
    lines += [
        "",
        "## UI Pages",
    ]
    for p in sorted(ui_pages):
        lines.append(f"- [{p}](/dist/{p}.html)")
    lines += [
        "",
        "## Core Capabilities",
        "- **Memory**: MemPalace (ChromaDB semantic) + user portrait + open loops engine",
        "- **Calendar / Reminders / Lists / Notes / People**: PostgreSQL, user-scoped, MCP-accessible",
        "- **Home Automation**: Home Assistant bridge (HA control, sensors, scenes)",
        "- **Voice**: Wyoming/Whisper transcription + TTS",
        "- **Push**: WebSocket /ws/push + proactive engine (morning brief, open loop follow-ups)",
        "- **Panel**: show_map, show_chart, show_image, open_touch_page, panel_browser_screenshot",
        "- **Web search**: DuckDuckGo scraping via web_search tool (no API key required)",
        "- **Self-improvement**: intent-miss review → Hermes/Multica proposal workflow (`self_improve` intent)",
        "- **Hermes engineering loop**: source context → small feature → cleanup pass → review/test",
        "- **Agent sync**: POST /api/system/agent-sync regenerates this file and all agent docs",
        "",
        "## Escalation Guide",
        "1. `web_search` — current events, live prices, news after training cutoff",
        "2. `escalate_to_hermes` — default for complex tasks, engineering, architecture, code review, planning, board repair, and Greptile loops",
        "3. `escalate_to_openclaw` — explicit/manual fallback; Hermes remains the default route",
    ]
    return "\n".join(lines) + "\n"


def _env_enabled(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


async def run_agent_sync() -> dict:
    """Run the full agent sync. Returns a status dict."""
    mcp_tools, skills, ui_pages = await asyncio.gather(
        _collect_mcp_tools(),
        _collect_openclaw_skills(),
        _collect_ui_pages(),
    )

    zoe_self = _build_zoe_self_md(mcp_tools, skills, ui_pages)
    compact = _build_compact(mcp_tools, skills)
    capabilities = _build_capabilities_md(mcp_tools, skills, ui_pages)

    results: dict = {
        "mcp_tools": len(mcp_tools),
        "skills": len(skills),
        "ui_pages": len(ui_pages),
    }

    # Write ZOE_SELF.md to OpenClaw workspace
    try:
        _OPENCLAW_ZOE_SELF.parent.mkdir(parents=True, exist_ok=True)
        _OPENCLAW_ZOE_SELF.write_text(zoe_self)
        results["openclaw_zoe_self"] = "updated"
        logger.info("agent_sync: wrote ZOE_SELF.md (%d chars) to %s", len(zoe_self), _OPENCLAW_ZOE_SELF)
    except Exception as exc:
        results["openclaw_zoe_self"] = f"error: {exc}"
        logger.warning("agent_sync: ZOE_SELF.md write failed: %s", exc)

    # Patch Hermes SOUL.md — live architecture (ZOE_SELF) + mission/charter (ZOE_WHY)
    patched = _patch_hermes_soul(_HERMES_SOUL, zoe_self, marker="ZOE_SELF")
    results["hermes_soul"] = "patched" if patched else "skipped"

    zoe_why = _build_zoe_why()
    patched_why = _patch_hermes_soul(_HERMES_SOUL, zoe_why, marker="ZOE_WHY")
    results["hermes_why"] = "patched" if patched_why else "skipped"

    # Write compact
    try:
        _ZOE_COMPACT.parent.mkdir(parents=True, exist_ok=True)
        _ZOE_COMPACT.write_text(compact + "\n")
        results["compact"] = "updated"
        logger.info("agent_sync: wrote compact (%d chars)", len(compact))
    except Exception as exc:
        results["compact"] = f"error: {exc}"
        logger.warning("agent_sync: compact write failed: %s", exc)

    # Write CAPABILITIES.md
    try:
        _CAPABILITIES_MD.write_text(capabilities)
        results["capabilities_md"] = "updated"
        logger.info("agent_sync: wrote CAPABILITIES.md (%d chars)", len(capabilities))
    except Exception as exc:
        results["capabilities_md"] = f"error: {exc}"
        logger.warning("agent_sync: CAPABILITIES.md write failed: %s", exc)


    results["status"] = "ok"
    return results
