/**
 * The harness workflow: scout -> implement -> verify -> openPR, in Flue's real
 * shape. Discovered by the CLI as the `harness` workflow.
 *
 * Run it:  flue run harness --input '{"issue": 715}'
 *
 * Flue's durability unit is THIS workflow (one bound agent + one action). The
 * phases are expressed as: the bound orchestrator agent (writable `local()`
 * sandbox over the Zoe checkout) delegating the read-only phases to the scout and
 * verifier SUBAGENTS via `session.task({ agent })`, with the deterministic git/PR
 * mechanics done in code. No `step.run()` — that helper does not exist in Flue.
 *
 * LAB ONLY: opens a PR, never merges. The harness model is the `openrouter/*`
 * model registered in ../src/app.ts, never the `:11434` voice brain.
 */
import { defineWorkflow } from '@flue/runtime';
import * as v from 'valibot';
import { loadConfig } from '../config.ts';
import { buildOrchestrator } from '../roles.ts';
import {
  captureDiff,
  commitAndPush,
  createBranch,
  fetchIssue,
  openPr,
  runVerify,
} from '../github.ts';

const cfg = loadConfig();

export default defineWorkflow({
  agent: buildOrchestrator(cfg.zoeCheckout),
  input: v.object({ issue: v.optional(v.number()) }),
  output: v.object({ prUrl: v.string(), verdict: v.string() }),

  async run({ harness, input, log }) {
    const issueNumber = input?.issue ?? cfg.targetIssue;
    const issue = await fetchIssue({ ...cfg, targetIssue: issueNumber });
    log.info('scouting issue', { issue: issue.number, title: issue.title });

    // Fresh branch off origin/main in the checkout the agent sandbox edits.
    const branch = `flue-spike/issue-${issue.number}-${Date.now()}`;
    await createBranch({ ...cfg, targetIssue: issueNumber }, branch);

    const session = await harness.session();

    // PHASE 1: scout (subagent) — read-only reasoning -> a plan.
    const plan = (
      await session.task(
        [
          `Scout GitHub issue #${issue.number} in ${cfg.githubRepo}.`,
          `Title: ${issue.title}`,
          '',
          issue.body || '(no body)',
          '',
          'Produce the minimal change plan.',
        ].join('\n'),
        { agent: 'scout' },
      )
    ).text;
    log.info('scout produced plan', { chars: plan.length });

    // PHASE 2: implement — the orchestrator agent edits files in its sandbox.
    const commitSubject =
      (
        await session.prompt(
          [
            `Plan:\n${plan}`,
            '',
            `Apply the smallest change in the checkout on branch ${branch}.`,
            'Reply with ONLY a conventional-commit subject line.',
          ].join('\n'),
        )
      ).text.trim() || `spike: address issue #${issue.number}`;

    const diff = await captureDiff(cfg);
    if (!diff.stat.trim()) {
      throw new Error('IMPLEMENT produced no diff; stopping loudly at the phase boundary.');
    }

    // PHASE 3: verify — run the check, then a subagent judges the evidence.
    const verify = await runVerify(cfg);
    const verdict = (
      await session.task(
        [
          `Diff (stat):\n${diff.stat}`,
          '',
          `Verify command exit ok: ${verify.ok}`,
          `Verify output:\n${verify.evidence}`,
          '',
          'PASS or FAIL?',
        ].join('\n'),
        { agent: 'verifier' },
      )
    ).text.trim();
    log.info('verifier verdict', { verdict: verdict.slice(0, 80) });

    if (!/^PASS/i.test(verdict)) {
      throw new Error(`VERIFY did not pass; not opening a PR.\nVerdict: ${verdict}`);
    }

    // PHASE 4: openPR (deterministic; never merges).
    await commitAndPush(cfg, branch, commitSubject);
    const cappedPatch =
      diff.patch.length > 48 * 1024
        ? `${diff.patch.slice(0, 48 * 1024)}\n…[truncated; see GitHub diff view]`
        : diff.patch;
    const body = [
      `Autonomous Flue-harness spike — issue #${issue.number}.`,
      '',
      `**Scout plan**\n\n${plan}`,
      '',
      `**Diff (stat)**\n\n\`\`\`\n${diff.stat}\n\`\`\``,
      '',
      `**Diff (patch)**\n\n<details><summary>show patch</summary>\n\n\`\`\`diff\n${cappedPatch}\n\`\`\`\n\n</details>`,
      '',
      `**Verify evidence**\n\n\`\`\`\n${verify.evidence}\n\`\`\``,
      '',
      `**Verifier verdict**\n\n${verdict}`,
      '',
      '> Generated by labs/flue-harness-spike (lab-only). Do not auto-merge.',
    ].join('\n');
    const prUrl = await openPr(cfg, branch, commitSubject, body);
    log.info('opened PR', { prUrl });

    return { prUrl, verdict };
  },
});
