#!/usr/bin/env python3
"""
Docker Compose Module Generator
================================

Generates docker-compose.modules.yml from enabled modules in config/modules.yaml

Usage:
  python tools/generate_module_compose.py
  python tools/generate_module_compose.py --validate-only
"""

import yaml
import sys
from pathlib import Path
from typing import Dict, List, Optional
import click


class ComposeGenerator:
    """Generate docker-compose.modules.yml from enabled modules."""
    
    def __init__(self, project_root: Path = None):
        self.project_root = project_root or Path.cwd()
        self.modules_dir = self.project_root / "modules"
        self.config_file = self.project_root / "config" / "modules.yaml"
        self.output_file = self.project_root / "docker-compose.modules.yml"
    
    def load_config(self) -> Dict:
        """Load modules configuration."""
        if not self.config_file.exists():
            return {"enabled_modules": [], "module_config": {}}
        
        try:
            return yaml.safe_load(self.config_file.read_text())
        except Exception as e:
            print(f"❌ Error reading config: {e}", file=sys.stderr)
            sys.exit(1)
    
    def get_enabled_modules(self) -> List[str]:
        """Get list of enabled module names."""
        config = self.load_config()
        return config.get("enabled_modules", [])
    
    def load_module_compose(self, module_name: str) -> Optional[Dict]:
        """Load a module's docker-compose.module.yml file."""
        compose_file = self.modules_dir / module_name / "docker-compose.module.yml"
        
        if not compose_file.exists():
            print(f"⚠️  Warning: {module_name} has no docker-compose.module.yml", file=sys.stderr)
            return None
        
        try:
            return yaml.safe_load(compose_file.read_text())
        except Exception as e:
            print(f"❌ Error reading {module_name} compose: {e}", file=sys.stderr)
            return None
    
    def generate(self) -> Dict:
        """Generate combined docker-compose.modules.yml."""
        enabled_modules = self.get_enabled_modules()
        
        if not enabled_modules:
            print("ℹ️  No modules enabled", file=sys.stderr)
            return {
                "services": {},
                "networks": {
                    "zoe-network": {
                        "name": "zoe-network",
                        "external": True
                    }
                }
            }
        
        print(f"📦 Generating compose for {len(enabled_modules)} modules:")
        for module in enabled_modules:
            print(f"   - {module}")
        
        # Start with base structure
        combined = {
            "services": {},
            "networks": {
                "zoe-network": {
                    "name": "zoe-network",
                    "external": True
                }
            }
        }
        
        # Merge each enabled module's compose file
        for module_name in enabled_modules:
            module_compose = self.load_module_compose(module_name)
            
            if not module_compose:
                continue
            
            # Merge services
            if "services" in module_compose:
                for service_name, service_config in module_compose["services"].items():
                    if service_name in combined["services"]:
                        print(f"⚠️  Warning: Service '{service_name}' already exists, skipping", file=sys.stderr)
                        continue
                    combined["services"][service_name] = service_config
                    print(f"   ✓ Added service: {service_name}")
            
            # Merge networks (networks should be external, so just validate)
            if "networks" in module_compose:
                module_networks = module_compose["networks"]
                if "zoe-network" not in module_networks:
                    print(f"⚠️  Warning: {module_name} should use zoe-network", file=sys.stderr)
            
            # Merge volumes if any
            if "volumes" in module_compose and module_compose["volumes"]:
                if "volumes" not in combined:
                    combined["volumes"] = {}
                combined["volumes"].update(module_compose["volumes"])
        
        return combined
    
    def write_compose(self, compose_data: Dict) -> bool:
        """Write the generated compose file."""
        try:
            # Add header comment
            header = """# ============================================================
# AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
# ============================================================
# This file is generated by tools/generate_module_compose.py
# Edit config/modules.yaml to enable/disable modules, then regenerate
# Generated: {}
# ============================================================

""".format(Path.cwd())
            
            compose_yaml = yaml.dump(compose_data, default_flow_style=False, sort_keys=False)
            self.output_file.write_text(header + compose_yaml)
            
            print(f"\n✓ Generated: {self.output_file}")
            print(f"  Services: {len(compose_data.get('services', {}))}")
            
            return True
        except Exception as e:
            print(f"❌ Error writing compose file: {e}", file=sys.stderr)
            return False
    
    def validate(self) -> bool:
        """Validate the generated compose file."""
        if not self.output_file.exists():
            print(f"❌ No generated compose file found at {self.output_file}", file=sys.stderr)
            return False
        
        try:
            compose_data = yaml.safe_load(self.output_file.read_text())
            
            # Basic validation
            if "services" not in compose_data:
                print("❌ No services defined", file=sys.stderr)
                return False
            
            # Check each service has required fields
            for service_name, service in compose_data["services"].items():
                if "container_name" not in service:
                    print(f"⚠️  Service {service_name} missing container_name", file=sys.stderr)
                
                if "networks" not in service or "zoe-network" not in service["networks"]:
                    print(f"⚠️  Service {service_name} not on zoe-network", file=sys.stderr)
            
            print(f"✓ Compose file validated: {len(compose_data['services'])} services")
            return True
            
        except Exception as e:
            print(f"❌ Validation error: {e}", file=sys.stderr)
            return False


@click.command()
@click.option('--validate-only', '-v', is_flag=True, help='Only validate, do not generate')
def main(validate_only):
    """Generate docker-compose.modules.yml from enabled modules."""
    generator = ComposeGenerator()
    
    if validate_only:
        success = generator.validate()
        sys.exit(0 if success else 1)
    
    # Generate
    compose_data = generator.generate()
    
    # Write
    success = generator.write_compose(compose_data)
    
    if success:
        # Validate
        if generator.validate():
            print(f"\n✅ Generation complete!")
            print(f"\nTo apply changes:")
            print(f"  docker compose -f docker-compose.yml -f docker-compose.modules.yml up -d")
        else:
            print(f"\n⚠️  Generated but validation failed")
            sys.exit(1)
    else:
        sys.exit(1)


if __name__ == '__main__':
    main()
