"""CAPABILITIES.md must match mcp_server.py's TOOLS exactly, in BOTH directions.

Why (2026-08-03): the file is regenerated by `agent_sync` inside zoe-data's
`ExecStartPre`, so a stale committed copy means every single service start
rewrites a TRACKED file. The live checkout is then dirty, and the deploy
readiness gate blocks — a service that reliably breaks its own deployment. It
happened with `web_browse`: a real tool (present in TOOLS) missing from the
committed snapshot.

BOTH directions are asserted, and that is the point (review: Codex). A one-way
check — "every documented tool exists in the source" — stays green in exactly
the failure case above, because a tool ADDED without regenerating the snapshot
leaves the documented set a strict subset. The stale-snapshot direction is the
one that actually recurs, so equality is the assertion.

TOOLS is read by AST rather than by importing mcp_server: the import pulls in
the whole service (DB, chroma, onnx) and would not survive the slim `ci_safe`
lane. `agent_sync._collect_mcp_tools` uses `t["name"]` off the same list, so
this reads the identical field from the identical literal.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

pytestmark = pytest.mark.ci_safe

ROOT = Path(__file__).resolve().parents[2]
CAPS = ROOT / "CAPABILITIES.md"
MCP = ROOT / "services" / "zoe-data" / "mcp_server.py"
SECTION = "## MCP Tools"


def _tools_from_source() -> set[str]:
    """Names in mcp_server.TOOLS, via AST (no import side effects)."""
    tree = ast.parse(MCP.read_text())
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(getattr(t, "id", None) == "TOOLS" for t in node.targets):
            continue
        assert isinstance(node.value, ast.List), "TOOLS is expected to be a list literal"
        names: set[str] = set()
        for entry in node.value.elts:
            if not isinstance(entry, ast.Dict):
                continue
            for k, v in zip(entry.keys, entry.values):
                if isinstance(k, ast.Constant) and k.value == "name" and isinstance(v, ast.Constant):
                    names.add(v.value)
        return names
    raise AssertionError("TOOLS list not found in mcp_server.py")


def _tools_from_doc() -> set[str]:
    """Names under the '## MCP Tools' heading only — the file lists OpenClaw
    skills and UI pages in the same bullet style, and those are not TOOLS."""
    names: set[str] = set()
    in_section = False
    for line in CAPS.read_text().splitlines():
        if line.startswith("## "):
            in_section = line.strip() == SECTION
            continue
        t = line.strip()
        if in_section and t.startswith("- `") and t.endswith("`"):
            names.add(t.strip("`- "))
    return names


def test_tools_list_is_parseable():
    """Guard the guard: if the AST shape changes, fail loudly rather than
    silently comparing an empty set against an empty set."""
    assert len(_tools_from_source()) > 10


def test_documented_tools_all_exist_in_source():
    doc, src = _tools_from_doc(), _tools_from_source()
    stale = doc - src
    assert not stale, (
        "CAPABILITIES.md documents tools that no longer exist in mcp_server.py "
        f"(remove them): {sorted(stale)}"
    )


def test_every_source_tool_is_documented():
    """The direction that actually recurs: a tool added without regenerating the
    snapshot. agent_sync then rewrites the tracked file on the live host and
    re-creates the deploy-blocking dirtiness."""
    doc, src = _tools_from_doc(), _tools_from_source()
    undocumented = src - doc
    assert not undocumented, (
        "mcp_server.py has tools missing from CAPABILITIES.md — regenerate it "
        "(agent_sync) and commit, or every zoe-data start will dirty a tracked "
        f"file and block the next deploy: {sorted(undocumented)}"
    )
